###
### Contains common comfyui service configuration
### common = shared between both dev and production
###
version: "3.8"
services:
  comfyui_common:
    build: ./
    image: quinninc/comfy:1.0.0
    container_name: comfyui-worker
